/**
 * Mock Data for HAC Dashboard 🐴
 *
 * Realistic demo data used until the scraping engine (Phase 9) is live.
 * Swap with real Supabase queries later — zero UI changes needed.
 */

// ─── Hackathons ──────────────────────────────────────────────
export const MOCK_HACKATHONS = [
  {
    id: "h1",
    title: "HackMIT 2025",
    organizer: "MIT",
    source: "mlh",
    source_url: "https://hackmit.org",
    image_url: null,
    location: "Cambridge, MA",
    is_online: false,
    start_date: "2025-10-14T09:00:00Z",
    end_date: "2025-10-15T21:00:00Z",
    registration_deadline: "2025-09-28T23:59:00Z",
    prize_pool: "$25,000",
    tags: ["AI/ML", "Web Dev", "Mobile"],
    difficulty: "intermediate",
    team_size_min: 2,
    team_size_max: 4,
    status: "upcoming",
    match_score: 94,
    is_hac_pick: true,
  },
  {
    id: "h2",
    title: "ETHGlobal New York",
    organizer: "ETHGlobal",
    source: "devpost",
    source_url: "https://ethglobal.com/events/newyork2025",
    image_url: null,
    location: "New York, NY",
    is_online: false,
    start_date: "2025-09-22T10:00:00Z",
    end_date: "2025-09-24T18:00:00Z",
    registration_deadline: "2025-09-15T23:59:00Z",
    prize_pool: "$100,000+",
    tags: ["Web3", "Blockchain", "DeFi"],
    difficulty: "advanced",
    team_size_min: 1,
    team_size_max: 5,
    status: "upcoming",
    match_score: 72,
    is_hac_pick: false,
  },
  {
    id: "h3",
    title: "Google Solution Challenge",
    organizer: "Google Developer Student Clubs",
    source: "devpost",
    source_url: "https://developers.google.com/community/gdsc-solution-challenge",
    image_url: null,
    location: "Online",
    is_online: true,
    start_date: "2025-11-01T00:00:00Z",
    end_date: "2026-03-31T23:59:00Z",
    registration_deadline: "2025-12-15T23:59:00Z",
    prize_pool: "$10,000",
    tags: ["Social Good", "Mobile", "Cloud"],
    difficulty: "all",
    team_size_min: 2,
    team_size_max: 4,
    status: "upcoming",
    match_score: 88,
    is_hac_pick: true,
  },
  {
    id: "h4",
    title: "MLH Global Hack Week: AI/ML",
    organizer: "Major League Hacking",
    source: "mlh",
    source_url: "https://ghw.mlh.io",
    image_url: null,
    location: "Online",
    is_online: true,
    start_date: "2025-08-11T12:00:00Z",
    end_date: "2025-08-17T23:59:00Z",
    registration_deadline: "2025-08-10T23:59:00Z",
    prize_pool: "Prizes + Swag",
    tags: ["AI/ML", "Data Science", "Python"],
    difficulty: "beginner",
    team_size_min: 1,
    team_size_max: 4,
    status: "upcoming",
    match_score: 91,
    is_hac_pick: false,
  },
  {
    id: "h5",
    title: "Unstop TechSprint 3.0",
    organizer: "Unstop",
    source: "unstop",
    source_url: "https://unstop.com/hackathons/techsprint-3",
    image_url: null,
    location: "Online",
    is_online: true,
    start_date: "2025-09-05T10:00:00Z",
    end_date: "2025-09-07T18:00:00Z",
    registration_deadline: "2025-09-01T23:59:00Z",
    prize_pool: "₹5,00,000",
    tags: ["Web Dev", "IoT", "Cloud"],
    difficulty: "intermediate",
    team_size_min: 2,
    team_size_max: 4,
    status: "upcoming",
    match_score: 83,
    is_hac_pick: false,
  },
  {
    id: "h6",
    title: "NASA Space Apps Challenge",
    organizer: "NASA",
    source: "devpost",
    source_url: "https://www.spaceappschallenge.org",
    image_url: null,
    location: "Worldwide (200+ cities)",
    is_online: false,
    start_date: "2025-10-04T09:00:00Z",
    end_date: "2025-10-06T17:00:00Z",
    registration_deadline: "2025-10-01T23:59:00Z",
    prize_pool: "Global Awards",
    tags: ["Space", "Data Science", "Hardware"],
    difficulty: "all",
    team_size_min: 1,
    team_size_max: 6,
    status: "upcoming",
    match_score: 67,
    is_hac_pick: false,
  },
  {
    id: "h7",
    title: "TreeHacks 2026",
    organizer: "Stanford University",
    source: "mlh",
    source_url: "https://treehacks.com",
    image_url: null,
    location: "Stanford, CA",
    is_online: false,
    start_date: "2026-02-14T18:00:00Z",
    end_date: "2026-02-16T12:00:00Z",
    registration_deadline: "2026-01-20T23:59:00Z",
    prize_pool: "$50,000+",
    tags: ["AI/ML", "Health", "Sustainability"],
    difficulty: "intermediate",
    team_size_min: 2,
    team_size_max: 4,
    status: "upcoming",
    match_score: 96,
    is_hac_pick: true,
  },
  {
    id: "h8",
    title: "HackTheBox CTF Finals",
    organizer: "Hack The Box",
    source: "hackerearth",
    source_url: "https://ctf.hackthebox.com",
    image_url: null,
    location: "Online",
    is_online: true,
    start_date: "2025-11-20T14:00:00Z",
    end_date: "2025-11-22T14:00:00Z",
    registration_deadline: "2025-11-10T23:59:00Z",
    prize_pool: "$15,000",
    tags: ["Cybersecurity", "CTF", "Networking"],
    difficulty: "advanced",
    team_size_min: 3,
    team_size_max: 5,
    status: "upcoming",
    match_score: 55,
    is_hac_pick: false,
  },
  {
    id: "h9",
    title: "Cal Hacks 11.0",
    organizer: "UC Berkeley",
    source: "mlh",
    source_url: "https://calhacks.io",
    image_url: null,
    location: "Berkeley, CA",
    is_online: false,
    start_date: "2025-10-18T18:00:00Z",
    end_date: "2025-10-20T12:00:00Z",
    registration_deadline: "2025-10-05T23:59:00Z",
    prize_pool: "$30,000",
    tags: ["AI/ML", "Fintech", "Social Good"],
    difficulty: "intermediate",
    team_size_min: 1,
    team_size_max: 4,
    status: "upcoming",
    match_score: 89,
    is_hac_pick: true,
  },
  {
    id: "h10",
    title: "Smart India Hackathon 2025",
    organizer: "Government of India",
    source: "unstop",
    source_url: "https://sih.gov.in",
    image_url: null,
    location: "India (Multiple Cities)",
    is_online: false,
    start_date: "2025-12-10T09:00:00Z",
    end_date: "2025-12-12T17:00:00Z",
    registration_deadline: "2025-11-25T23:59:00Z",
    prize_pool: "₹1,00,000 per problem",
    tags: ["Civic Tech", "AI/ML", "IoT"],
    difficulty: "all",
    team_size_min: 6,
    team_size_max: 6,
    status: "upcoming",
    match_score: 78,
    is_hac_pick: false,
  },
  {
    id: "h11",
    title: "PennApps XXIV",
    organizer: "University of Pennsylvania",
    source: "mlh",
    source_url: "https://pennapps.com",
    image_url: null,
    location: "Philadelphia, PA",
    is_online: false,
    start_date: "2025-09-12T17:00:00Z",
    end_date: "2025-09-14T12:00:00Z",
    registration_deadline: "2025-08-30T23:59:00Z",
    prize_pool: "$20,000",
    tags: ["Web Dev", "AI/ML", "Mobile"],
    difficulty: "intermediate",
    team_size_min: 1,
    team_size_max: 4,
    status: "upcoming",
    match_score: 85,
    is_hac_pick: false,
  },
  {
    id: "h12",
    title: "Buildspace Nights & Weekends S5",
    organizer: "Buildspace",
    source: "devpost",
    source_url: "https://buildspace.so/nw",
    image_url: null,
    location: "Online → SF Demo Day",
    is_online: true,
    start_date: "2025-10-01T00:00:00Z",
    end_date: "2025-12-15T23:59:00Z",
    registration_deadline: "2025-09-20T23:59:00Z",
    prize_pool: "Investor Intros",
    tags: ["Startup", "Product", "AI/ML"],
    difficulty: "all",
    team_size_min: 1,
    team_size_max: 3,
    status: "upcoming",
    match_score: 92,
    is_hac_pick: true,
  },
];


// ─── HAC Tips ──────────────────────────────────────────────────
export const HAC_TIPS = [
  "You know what's scarier than a production bug at 3 AM? Not having a hackathon to flex on your resume. 🐴",
  "Pro tip: Read the judging criteria BEFORE you start coding. I know, revolutionary. 😏",
  "Your README is your pitch deck. If it sucks, judges assume your code does too. No pressure.",
  "Sleep is a feature, not a bug. Well-rested hackers write better code. Trust the horse. 💤",
  "\"I'll just use a tutorial\" — Famous last words of every hackathon loser. Build something weird. 🔥",
  "3 new hackathons dropped today. Your Netflix queue can wait, champion.",
  "The best hackathon projects solve REAL problems. The worst ones are 'Uber for laundry'. Don't be that team.",
  "Fun fact: 73% of hackathon winners practiced their demo at least 5 times. The other 27% are lying. 🎤",
  "Hot take: Your tech stack doesn't matter if your idea is boring. HTML + passion beats React + boredom.",
  "You haven't opened HAC in 2 days. Did you forget about me or are you out there winning hackathons without me? 😤",
  "Looking for teammates? Say less. I'm basically LinkedIn but actually useful. 🤝",
  "Deadline in 48 hours and you haven't started? Bold strategy. Let's see if it pays off. ⏰",
  "Every hackathon you skip is a $10K prize pool someone else takes. Just saying. 💰",
  "Stop comparing your Day 1 to someone else's Day 100. Start. Build. Ship. 🚀",
  "Your code doesn't need to be perfect. It needs to work during the demo. Priorities. 😂",
  "I found 5 hackathons matching your skills. That's 5 chances to put 'hackathon winner' in your bio. 🏆",
  "Remember: hackathons are 80% teamwork, 15% code, and 5% caffeine. Get a good team.",
  "You code in Python AND JavaScript? Mans playing both sides. Respect. 😏",
  "$10K prize pool? Bro, that's your entire semester's rent. Get on it. 💸",
  "The commit history tells a story. Make sure yours doesn't say 'fixed bug' 47 times. 📝",
  "Online hackathon tip: Keep your camera on during judging. Judges trust faces more than profile pics.",
  "If your project name is a pun, you're already in the top 30%. Judges love puns. I'm a horse, I know things.",
];


// ─── Recent Activity Feed ──────────────────────────────────────
export const MOCK_ACTIVITY = [
  {
    id: "a1",
    type: "new_match",
    title: "New match found",
    description: "TreeHacks 2026 matches your AI/ML skills — 96% match score!",
    hackathon_id: "h7",
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(), // 30 min ago
  },
  {
    id: "a2",
    type: "bookmark",
    title: "Hackathon bookmarked",
    description: "You saved HackMIT 2025 to your watchlist",
    hackathon_id: "h1",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), // 2 hours ago
  },
  {
    id: "a3",
    type: "new_match",
    title: "5 new hackathons discovered",
    description: "HAC scraped 5 new competitions matching your profile",
    hackathon_id: null,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(), // 6 hours ago
  },
  {
    id: "a4",
    type: "deadline_warning",
    title: "Deadline approaching!",
    description: "PennApps XXIV registration closes in 3 days",
    hackathon_id: "h11",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(), // 12 hours ago
  },
  {
    id: "a5",
    type: "profile_update",
    title: "Profile strength increased",
    description: "Adding 'Python' and 'TensorFlow' boosted your match quality by 12%",
    hackathon_id: null,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), // 1 day ago
  },
  {
    id: "a6",
    type: "new_match",
    title: "HAC's Pick! 🐴",
    description: "Buildspace N&W S5 is perfect for you — 92% match + investor intros",
    hackathon_id: "h12",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(), // 1.5 days ago
  },
];


// ─── Dashboard Quick Stats ─────────────────────────────────────
export const MOCK_STATS = {
  activeHackathons: 12,
  bookmarked: 4,
  upcomingDeadlines: 3,
  avgMatchScore: 84,
};


// ─── Source Badge Colors ────────────────────────────────────────
export const SOURCE_COLORS = {
  mlh: { bg: "rgba(229, 57, 53, 0.12)", text: "#E53935", border: "rgba(229, 57, 53, 0.3)" },
  devpost: { bg: "rgba(0, 133, 255, 0.12)", text: "#0085FF", border: "rgba(0, 133, 255, 0.3)" },
  unstop: { bg: "rgba(255, 152, 0, 0.12)", text: "#FF9800", border: "rgba(255, 152, 0, 0.3)" },
  hackerearth: { bg: "rgba(46, 204, 113, 0.12)", text: "#2ECC71", border: "rgba(46, 204, 113, 0.3)" },
};


// ─── Activity Icon Map ──────────────────────────────────────────
export const ACTIVITY_ICONS = {
  new_match: "🎯",
  bookmark: "📌",
  deadline_warning: "⏰",
  profile_update: "👤",
  team_invite: "👥",
};
