/**
 * Mock Data for HAC Dashboard 🐴
 *
 * Realistic demo data used until the scraping engine (Phase 9) is live.
 * Swap with real Supabase queries later — zero UI changes needed.
 */

// ─── Hackathons ──────────────────────────────────────────────
export const MOCK_HACKATHONS = [
  {
    id: "h1",
    title: "HackMIT 2025",
    organizer: "MIT",
    source: "mlh",
    source_url: "https://hackmit.org",
    registration_url: "https://hackmit.org/register",
    description: "MIT's flagship hackathon brings together 1,000+ hackers for 24 hours of building. Workshops, mentors from top tech companies, and $25K in prizes. Projects judged on creativity, technical complexity, and real-world impact.",
    image_url: null,
    location: "Cambridge, MA",
    is_online: false,
    start_date: "2025-10-14T09:00:00Z",
    end_date: "2025-10-15T21:00:00Z",
    registration_deadline: "2025-09-28T23:59:00Z",
    prize_pool: "$25,000",
    tags: ["AI/ML", "Web Dev", "Mobile"],
    difficulty: "intermediate",
    team_size_min: 2,
    team_size_max: 4,
    status: "upcoming",
    match_score: 94,
    is_hac_pick: true,
  },
  {
    id: "h2",
    title: "ETHGlobal New York",
    organizer: "ETHGlobal",
    source: "devpost",
    source_url: "https://ethglobal.com/events/newyork2025",
    registration_url: "https://ethglobal.com/events/newyork2025/apply",
    description: "The premier Web3 hackathon returns to NYC. Build the next generation of decentralized applications. $100K+ in prizes from top blockchain protocols. Perfect for developers exploring DeFi, NFTs, and on-chain infrastructure.",
    image_url: null,
    location: "New York, NY",
    is_online: false,
    start_date: "2025-09-22T10:00:00Z",
    end_date: "2025-09-24T18:00:00Z",
    registration_deadline: "2025-09-15T23:59:00Z",
    prize_pool: "$100,000+",
    tags: ["Web3", "Blockchain", "DeFi"],
    difficulty: "advanced",
    team_size_min: 1,
    team_size_max: 5,
    status: "upcoming",
    match_score: 72,
    is_hac_pick: false,
  },
  {
    id: "h3",
    title: "Google Solution Challenge",
    organizer: "Google Developer Student Clubs",
    source: "devpost",
    source_url: "https://developers.google.com/community/gdsc-solution-challenge",
    registration_url: "https://developers.google.com/community/gdsc-solution-challenge/register",
    description: "Use Google technology to address one of the United Nations' 17 Sustainable Development Goals. Open to all university students worldwide. Build mobile apps, web apps, or ML solutions that create social impact.",
    image_url: null,
    location: "Online",
    is_online: true,
    start_date: "2025-11-01T00:00:00Z",
    end_date: "2026-03-31T23:59:00Z",
    registration_deadline: "2025-12-15T23:59:00Z",
    prize_pool: "$10,000",
    tags: ["Social Good", "Mobile", "Cloud"],
    difficulty: "all",
    team_size_min: 2,
    team_size_max: 4,
    status: "upcoming",
    match_score: 88,
    is_hac_pick: true,
  },
  {
    id: "h4",
    title: "MLH Global Hack Week: AI/ML",
    organizer: "Major League Hacking",
    source: "mlh",
    source_url: "https://ghw.mlh.io",
    registration_url: "https://ghw.mlh.io/register",
    description: "A week-long celebration of AI and machine learning by MLH. Beginner-friendly workshops, daily challenges, and tons of swag. Build projects using TensorFlow, PyTorch, or any ML framework of your choice.",
    image_url: null,
    location: "Online",
    is_online: true,
    start_date: "2025-08-11T12:00:00Z",
    end_date: "2025-08-17T23:59:00Z",
    registration_deadline: "2025-08-10T23:59:00Z",
    prize_pool: "Prizes + Swag",
    tags: ["AI/ML", "Data Science", "Python"],
    difficulty: "beginner",
    team_size_min: 1,
    team_size_max: 4,
    status: "upcoming",
    match_score: 91,
    is_hac_pick: false,
  },
  {
    id: "h5",
    title: "Unstop TechSprint 3.0",
    organizer: "Unstop",
    source: "unstop",
    source_url: "https://unstop.com/hackathons/techsprint-3",
    registration_url: "https://unstop.com/hackathons/techsprint-3/register",
    description: "India's fastest-growing tech hackathon. Build innovative solutions in Web Dev, IoT, or Cloud computing. Open to students and professionals. ₹5 lakh prize pool with internship opportunities from partner companies.",
    image_url: null,
    location: "Online",
    is_online: true,
    start_date: "2025-09-05T10:00:00Z",
    end_date: "2025-09-07T18:00:00Z",
    registration_deadline: "2025-09-01T23:59:00Z",
    prize_pool: "₹5,00,000",
    tags: ["Web Dev", "IoT", "Cloud"],
    difficulty: "intermediate",
    team_size_min: 2,
    team_size_max: 4,
    status: "upcoming",
    match_score: 83,
    is_hac_pick: false,
  },
  {
    id: "h6",
    title: "NASA Space Apps Challenge",
    organizer: "NASA",
    source: "devpost",
    source_url: "https://www.spaceappschallenge.org",
    registration_url: "https://www.spaceappschallenge.org/register",
    description: "NASA's international hackathon invites coders, scientists, and creatives to solve challenges using open NASA data. Hosted simultaneously in 200+ cities worldwide. Winners get recognized by NASA leadership.",
    image_url: null,
    location: "Worldwide (200+ cities)",
    is_online: false,
    start_date: "2025-10-04T09:00:00Z",
    end_date: "2025-10-06T17:00:00Z",
    registration_deadline: "2025-10-01T23:59:00Z",
    prize_pool: "Global Awards",
    tags: ["Space", "Data Science", "Hardware"],
    difficulty: "all",
    team_size_min: 1,
    team_size_max: 6,
    status: "upcoming",
    match_score: 67,
    is_hac_pick: false,
  },
  {
    id: "h7",
    title: "TreeHacks 2026",
    organizer: "Stanford University",
    source: "mlh",
    source_url: "https://treehacks.com",
    registration_url: "https://treehacks.com/apply",
    description: "Stanford's premier hackathon focused on hacking for social good. Verticals include Health, Sustainability, and New Frontiers. $50K+ in prizes, top-tier mentors, and a beautiful campus venue.",
    image_url: null,
    location: "Stanford, CA",
    is_online: false,
    start_date: "2026-02-14T18:00:00Z",
    end_date: "2026-02-16T12:00:00Z",
    registration_deadline: "2026-01-20T23:59:00Z",
    prize_pool: "$50,000+",
    tags: ["AI/ML", "Health", "Sustainability"],
    difficulty: "intermediate",
    team_size_min: 2,
    team_size_max: 4,
    status: "upcoming",
    match_score: 96,
    is_hac_pick: true,
  },
  {
    id: "h8",
    title: "HackTheBox CTF Finals",
    organizer: "Hack The Box",
    source: "hackerearth",
    source_url: "https://ctf.hackthebox.com",
    registration_url: "https://ctf.hackthebox.com/register",
    description: "The ultimate Capture The Flag cybersecurity competition. Solve challenges spanning web exploitation, reverse engineering, cryptography, and network forensics. For serious security enthusiasts only.",
    image_url: null,
    location: "Online",
    is_online: true,
    start_date: "2025-11-20T14:00:00Z",
    end_date: "2025-11-22T14:00:00Z",
    registration_deadline: "2025-11-10T23:59:00Z",
    prize_pool: "$15,000",
    tags: ["Cybersecurity", "CTF", "Networking"],
    difficulty: "advanced",
    team_size_min: 3,
    team_size_max: 5,
    status: "upcoming",
    match_score: 55,
    is_hac_pick: false,
  },
  {
    id: "h9",
    title: "Cal Hacks 11.0",
    organizer: "UC Berkeley",
    source: "mlh",
    source_url: "https://calhacks.io",
    registration_url: "https://calhacks.io/apply",
    description: "UC Berkeley's largest collegiate hackathon. 2,000+ hackers, 36 hours, $30K in prizes. Tracks include AI/ML, Fintech, and Social Good. Free food, Red Bull, and midnight ramen runs included.",
    image_url: null,
    location: "Berkeley, CA",
    is_online: false,
    start_date: "2025-10-18T18:00:00Z",
    end_date: "2025-10-20T12:00:00Z",
    registration_deadline: "2025-10-05T23:59:00Z",
    prize_pool: "$30,000",
    tags: ["AI/ML", "Fintech", "Social Good"],
    difficulty: "intermediate",
    team_size_min: 1,
    team_size_max: 4,
    status: "upcoming",
    match_score: 89,
    is_hac_pick: true,
  },
  {
    id: "h10",
    title: "Smart India Hackathon 2025",
    organizer: "Government of India",
    source: "unstop",
    source_url: "https://sih.gov.in",
    registration_url: "https://sih.gov.in/register",
    description: "India's biggest government-backed hackathon. Solve problem statements from 50+ ministries and organizations. Fixed team size of 6. Winners get ₹1 lakh per problem + implementation opportunities with the government.",
    image_url: null,
    location: "India (Multiple Cities)",
    is_online: false,
    start_date: "2025-12-10T09:00:00Z",
    end_date: "2025-12-12T17:00:00Z",
    registration_deadline: "2025-11-25T23:59:00Z",
    prize_pool: "₹1,00,000 per problem",
    tags: ["Civic Tech", "AI/ML", "IoT"],
    difficulty: "all",
    team_size_min: 6,
    team_size_max: 6,
    status: "upcoming",
    match_score: 78,
    is_hac_pick: false,
  },
  {
    id: "h11",
    title: "PennApps XXIV",
    organizer: "University of Pennsylvania",
    source: "mlh",
    source_url: "https://pennapps.com",
    registration_url: "https://pennapps.com/apply",
    description: "One of the oldest and most prestigious collegiate hackathons, hosted at UPenn. 500+ hackers, 36 hours, $20K in prizes. Known for its competitive atmosphere and strong alumni network.",
    image_url: null,
    location: "Philadelphia, PA",
    is_online: false,
    start_date: "2025-09-12T17:00:00Z",
    end_date: "2025-09-14T12:00:00Z",
    registration_deadline: "2025-08-30T23:59:00Z",
    prize_pool: "$20,000",
    tags: ["Web Dev", "AI/ML", "Mobile"],
    difficulty: "intermediate",
    team_size_min: 1,
    team_size_max: 4,
    status: "upcoming",
    match_score: 85,
    is_hac_pick: false,
  },
  {
    id: "h12",
    title: "Buildspace Nights & Weekends S5",
    organizer: "Buildspace",
    source: "devpost",
    source_url: "https://buildspace.so/nw",
    registration_url: "https://buildspace.so/nw/apply",
    description: "Not your typical hackathon. A 6-week build program where you ship a real product. Top builders get flown to SF for Demo Day and introduced to YC-tier investors. Build in public, ship fast, get funded.",
    image_url: null,
    location: "Online → SF Demo Day",
    is_online: true,
    start_date: "2025-10-01T00:00:00Z",
    end_date: "2025-12-15T23:59:00Z",
    registration_deadline: "2025-09-20T23:59:00Z",
    prize_pool: "Investor Intros",
    tags: ["Startup", "Product", "AI/ML"],
    difficulty: "all",
    team_size_min: 1,
    team_size_max: 3,
    status: "upcoming",
    match_score: 92,
    is_hac_pick: true,
  },
];


// ─── HAC Tips ──────────────────────────────────────────────────
export const HAC_TIPS = [
  "You know what's scarier than a production bug at 3 AM? Not having a hackathon to flex on your resume. 🐴",
  "Pro tip: Read the judging criteria BEFORE you start coding. I know, revolutionary. 😏",
  "Your README is your pitch deck. If it sucks, judges assume your code does too. No pressure.",
  "Sleep is a feature, not a bug. Well-rested hackers write better code. Trust the horse. 💤",
  "\"I'll just use a tutorial\" — Famous last words of every hackathon loser. Build something weird. 🔥",
  "3 new hackathons dropped today. Your Netflix queue can wait, champion.",
  "The best hackathon projects solve REAL problems. The worst ones are 'Uber for laundry'. Don't be that team.",
  "Fun fact: 73% of hackathon winners practiced their demo at least 5 times. The other 27% are lying. 🎤",
  "Hot take: Your tech stack doesn't matter if your idea is boring. HTML + passion beats React + boredom.",
  "You haven't opened HAC in 2 days. Did you forget about me or are you out there winning hackathons without me? 😤",
  "Looking for teammates? Say less. I'm basically LinkedIn but actually useful. 🤝",
  "Deadline in 48 hours and you haven't started? Bold strategy. Let's see if it pays off. ⏰",
  "Every hackathon you skip is a $10K prize pool someone else takes. Just saying. 💰",
  "Stop comparing your Day 1 to someone else's Day 100. Start. Build. Ship. 🚀",
  "Your code doesn't need to be perfect. It needs to work during the demo. Priorities. 😂",
  "I found 5 hackathons matching your skills. That's 5 chances to put 'hackathon winner' in your bio. 🏆",
  "Remember: hackathons are 80% teamwork, 15% code, and 5% caffeine. Get a good team.",
  "You code in Python AND JavaScript? Mans playing both sides. Respect. 😏",
  "$10K prize pool? Bro, that's your entire semester's rent. Get on it. 💸",
  "The commit history tells a story. Make sure yours doesn't say 'fixed bug' 47 times. 📝",
  "Online hackathon tip: Keep your camera on during judging. Judges trust faces more than profile pics.",
  "If your project name is a pun, you're already in the top 30%. Judges love puns. I'm a horse, I know things.",
];


// ─── Recent Activity Feed ──────────────────────────────────────
export const MOCK_ACTIVITY = [
  {
    id: "a1",
    type: "new_match",
    title: "New match found",
    description: "TreeHacks 2026 matches your AI/ML skills — 96% match score!",
    hackathon_id: "h7",
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(), // 30 min ago
  },
  {
    id: "a2",
    type: "bookmark",
    title: "Hackathon bookmarked",
    description: "You saved HackMIT 2025 to your watchlist",
    hackathon_id: "h1",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), // 2 hours ago
  },
  {
    id: "a3",
    type: "new_match",
    title: "5 new hackathons discovered",
    description: "HAC scraped 5 new competitions matching your profile",
    hackathon_id: null,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(), // 6 hours ago
  },
  {
    id: "a4",
    type: "deadline_warning",
    title: "Deadline approaching!",
    description: "PennApps XXIV registration closes in 3 days",
    hackathon_id: "h11",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(), // 12 hours ago
  },
  {
    id: "a5",
    type: "profile_update",
    title: "Profile strength increased",
    description: "Adding 'Python' and 'TensorFlow' boosted your match quality by 12%",
    hackathon_id: null,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), // 1 day ago
  },
  {
    id: "a6",
    type: "new_match",
    title: "HAC's Pick! 🐴",
    description: "Buildspace N&W S5 is perfect for you — 92% match + investor intros",
    hackathon_id: "h12",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(), // 1.5 days ago
  },
];


// ─── Dashboard Quick Stats ─────────────────────────────────────
export const MOCK_STATS = {
  activeHackathons: 12,
  bookmarked: 4,
  upcomingDeadlines: 3,
  avgMatchScore: 84,
};


// ─── Source Badge Colors ────────────────────────────────────────
export const SOURCE_COLORS = {
  mlh: { bg: "rgba(229, 57, 53, 0.12)", text: "#E53935", border: "rgba(229, 57, 53, 0.3)" },
  devpost: { bg: "rgba(0, 133, 255, 0.12)", text: "#0085FF", border: "rgba(0, 133, 255, 0.3)" },
  unstop: { bg: "rgba(255, 152, 0, 0.12)", text: "#FF9800", border: "rgba(255, 152, 0, 0.3)" },
  hackerearth: { bg: "rgba(46, 204, 113, 0.12)", text: "#2ECC71", border: "rgba(46, 204, 113, 0.3)" },
};


// ─── Activity Icon Map ──────────────────────────────────────────
export const ACTIVITY_ICONS = {
  new_match: "🎯",
  bookmark: "📌",
  deadline_warning: "⏰",
  profile_update: "👤",
  team_invite: "👥",
};


// ─── Mock Teams ──────────────────────────────────────────────
export const MOCK_TEAMS = [
  {
    id: "t1",
    name: "Neural Knights",
    hackathon_id: "h7",
    hackathon_title: "TreeHacks 2026",
    description: "Building an AI-powered mental health companion app. Looking for a strong frontend dev and someone who knows their way around NLP pipelines.",
    created_by: "u1",
    looking_for: ["React", "NLP", "UI/UX Design"],
    max_members: 4,
    is_open: true,
    members: [
      { id: "u1", name: "Arjun Patel", avatar: null, role: "leader" },
      { id: "u2", name: "Maya Chen", avatar: null, role: "member" },
    ],
    created_at: "2025-09-10T08:00:00Z",
  },
  {
    id: "t2",
    name: "Byte Bandits",
    hackathon_id: "h1",
    hackathon_title: "HackMIT 2025",
    description: "We're building a decentralized study group platform with AI-generated flashcards. Need a backend wizard and a blockchain enthusiast.",
    created_by: "u3",
    looking_for: ["Node.js", "Solidity", "PostgreSQL"],
    max_members: 4,
    is_open: true,
    members: [
      { id: "u3", name: "Jordan Lee", avatar: null, role: "leader" },
      { id: "u4", name: "Priya Sharma", avatar: null, role: "member" },
      { id: "u5", name: "Alex Kim", avatar: null, role: "member" },
    ],
    created_at: "2025-09-08T14:30:00Z",
  },
  {
    id: "t3",
    name: "Green Machines",
    hackathon_id: "h3",
    hackathon_title: "Google Solution Challenge",
    description: "Tackling UN SDG #13 (Climate Action) with a carbon footprint tracker that gamifies sustainability. Mobile-first approach.",
    created_by: "u6",
    looking_for: ["Flutter", "Firebase", "Data Visualization"],
    max_members: 4,
    is_open: true,
    members: [
      { id: "u6", name: "Sam Williams", avatar: null, role: "leader" },
    ],
    created_at: "2025-10-01T10:00:00Z",
  },
  {
    id: "t4",
    name: "Ctrl+Alt+Elite",
    hackathon_id: "h9",
    hackathon_title: "Cal Hacks 11.0",
    description: "Fintech project: building a peer-to-peer micro-lending platform for college students. Strong ML background for credit scoring.",
    created_by: "u7",
    looking_for: ["Python", "TensorFlow", "Fintech"],
    max_members: 4,
    is_open: true,
    members: [
      { id: "u7", name: "Emma Davis", avatar: null, role: "leader" },
      { id: "u8", name: "Ravi Kumar", avatar: null, role: "member" },
    ],
    created_at: "2025-09-15T09:00:00Z",
  },
  {
    id: "t5",
    name: "Sudo Squad",
    hackathon_id: "h10",
    hackathon_title: "Smart India Hackathon 2025",
    description: "Working on a blockchain-based land registry system for rural India. Need exactly 6 members as per SIH rules.",
    created_by: "u9",
    looking_for: ["Blockchain", "React", "GIS"],
    max_members: 6,
    is_open: true,
    members: [
      { id: "u9", name: "Aditya Gupta", avatar: null, role: "leader" },
      { id: "u10", name: "Neha Verma", avatar: null, role: "member" },
      { id: "u11", name: "Rohan Singh", avatar: null, role: "member" },
      { id: "u12", name: "Tanvi Joshi", avatar: null, role: "member" },
    ],
    created_at: "2025-11-01T11:00:00Z",
  },
  {
    id: "t6",
    name: "Pixel Pirates",
    hackathon_id: "h12",
    hackathon_title: "Buildspace Nights & Weekends S5",
    description: "Building an AI art marketplace where creators can sell custom-trained LoRA models. Ship fast, get funded. 🚀",
    created_by: "u13",
    looking_for: ["Next.js", "Stripe API", "ML/Diffusion Models"],
    max_members: 3,
    is_open: false,
    members: [
      { id: "u13", name: "Kai Nakamura", avatar: null, role: "leader" },
      { id: "u14", name: "Luna Park", avatar: null, role: "member" },
      { id: "u15", name: "Dev Patel", avatar: null, role: "member" },
    ],
    created_at: "2025-09-20T16:00:00Z",
  },
];

